use ailen_estilista ; 

-- ELEGI LA TABLA CLIENTES DE MI PROYECTO PARA AUDITAR--


drop table if  exists LOG_AUDITORIA_CLIENTES ; 
CREATE TABLE IF NOT EXISTS LOG_AUDITORIA_CLIENTES
(
ID_LOG INT AUTO_INCREMENT ,
ID_CLIENTES INT, 
APELLIDO varchar (50) , 
TELEFONO INT ,
DIRECCION VARCHAR (100),
NOMBRE_DE_ACCION VARCHAR(10) ,
NOMBRE_TABLA VARCHAR(50) ,
USUARIO VARCHAR(100) , 
FECHA DATE ,
HORA TIME, 
PRIMARY KEY (ID_LOG)
)
; 


-- ESTE TRIGGER LO QUE CONTROLA ES CUANDO SE AGREGA UN NUEVO CLIENTE A LA DB -- 

 DROP TRIGGER IF EXISTS TRG_LOG_CLIENTES ; 
 DELIMITER //
CREATE TRIGGER TRG_LOG_CLIENTES AFTER insert ON ailen_estilista.CLIENTES 
FOR EACH ROW 
BEGIN

INSERT INTO LOG_AUDITORIA_CLIENTES ( ID_CLIENTES, APELLIDO, TELEFONO, DIRECCION, NOMBRE_DE_ACCION , NOMBRE_TABLA, USUARIO, FECHA, HORA  ) 
VALUES ( NEW.ID_CLIENTES ,  NEW.APELLIDO, NEW.TELEFONO, NEW.DIRECCION, 'INSERT', 'CLIENTES', CURRENT_USER () , current_date() , current_time() )  ; 

END//
DELIMITER ;

-- A CONTINUACION DEJO UN EJEMPLO COEMNTADO PARA PONER A PRUEBA EL TRIGGER --

-- INSERT INTO CLIENTES ( APELLIDO , TELEFONO  , DIRECCION , EMAIL  ) 
          VALUES      ('PEREZ',1189765678,'CHAPELCO  90','PEREZ_789@GMAIL.COM') ; 
--  INSERT INTO clientes  ( nombre , apellido , telefono , direccion , email )
             VALUES ( 'PRISCILA' , 'BEJARANO ', 1136758490 , ' GIRASOLES 56 ' , ' BEJARANO_72@GMAIL.COM ' ) ;
--  INSERT INTO clientes  ( nombre , apellido , telefono , direccion , email )
             VALUES ( 'ANTONELA' , 'OJEDA ', 1136758490 , ' MONTANIESES 45 ' , ' ANTO.OJEDA@GMAIL.COM ' ) ;
 
--  SELECT * FROM log_auditoria_clientes ; 

-- ESTE TRIGGER LO QUE CONTROLA ES SI UN USUARIO CAMBIA LA DIRECCION  DEL CLIENTE -- 

DROP TRIGGER IF EXISTS TRG_LOG_CLIENTES_UPDATE ; 
 DELIMITER //
CREATE TRIGGER TRG_LOG_CLIENTES_UPDATE BEFORE update ON ailen_estilista.CLIENTES 
FOR EACH ROW 
BEGIN

INSERT INTO LOG_AUDITORIA_CLIENTES ( ID_CLIENTES, APELLIDO, TELEFONO, DIRECCION, NOMBRE_DE_ACCION , NOMBRE_TABLA, USUARIO, FECHA, HORA  ) 
                          VALUES ( OLD.ID_CLIENTES, OLD.APELLIDO, OLD.TELEFONO, concat ('CAMPO ANTERIOR : ', OLD.DIRECCION  ,'  CAMPO NUEVO : ' , NEW.DIRECCION ),
                                'UPDATE' ,
                                ' CLIENTES ' ,
                                CURRENT_USER () , 
                                current_date() , 
                                current_time() ) ; 
                                
				
END //
DELIMITER ;

-- A CONTINUACION DEJO COMENTADO UN EJEMPLO PARA PONER A PRUEBA ESTE TRIGGER -- 
-- SELECT * FROM CLIENTES ; 
-- UPDATE CLIENTES SET DIRECCION = ' AV SAN MARTIN 49 ' WHERE ID_CLIENTES = 6 ; 
-- SELECT * FROM log_auditoria_clientes ; 



-- VOY A ELEGIR LA TABLA SERVICIO PARA AUDITAR EM CAMBIO DE LOS PRECIOS -- 

drop table if  exists LOG_AUDITORIA_SERVICIO ;
CREATE TABLE IF NOT EXISTS LOG_AUDITORIA_SERVICIO
(
ID_LOG INT AUTO_INCREMENT ,
ID_SERVICIO INT , 
PRECIO INT ,
NOMBRE_DE_ACCION VARCHAR(10) ,
NOMBRE_TABLA VARCHAR(50) ,
USUARIO VARCHAR(100) , 
FECHA DATE ,
HORA TIME, 
PRIMARY KEY (ID_LOG)
)
; 

DROP TRIGGER IF EXISTS TRG_LOG_SERVICIO ; 
 DELIMITER //
CREATE TRIGGER TRG_LOG_SERVICIO  AFTER UPDATE ON ailen_estilista.SERVICIOS 
FOR EACH ROW 
BEGIN

INSERT INTO LOG_AUDITORIA_SERVICIO ( ID_SERVICIO, PRECIO, NOMBRE_DE_ACCION, NOMBRE_TABLA, USUARIO, FECHA, HORA) 
                         VALUES     ( OLD.ID_SERVICIO,OLD.PRECIO, 'UPDATE' , 'SERVICIOS', CURRENT_USER () , CURRENT_DATE (), CURRENT_TIME () ) ;
                                

END //
DELIMITER ;

-- A CONTINUACION DEJO UN EJEMPLO COMENTADO PARA PONER A PROUEBA LA AUDITORIA-- 
-- SELECT * FROM SERVICIOS; 
-- UPDATE SERVICIOS SET PRECIO =300 WHERE ID_SERVICIO = 2 ; 

-- SELECT * FROM log_auditoria_servicio ; 